<?php
    // JE DÉTRUIT LA SESSION ACTUELLE POUR QUE $_SESSION SOIT VIDE DE NOUVEAU COMME A L'ARRIVEE SUR L'APPLICATION
    unset($_SESSION);
    // JE SUIS REDIRIGER VERS LA PAGE D'ACCEUIL EN TANT QUE SIMPLE VISITEUR
    header("location: ../../../index.php");
?>